description: Canada provides this base amount for the BPA.
values:
  2020-01-01: 12_298
  2021-01-01: 12_421
  2022-01-01: 12_719
  2023-01-01: 13_521
  2024-01-01: 14_156
  2025-01-01: 14_538
metadata:
  unit: currency-CAD
  period: year
  label: Basic personal amount base
  reference:
    - title: Government of Canada - Basic Personal amount
      href: https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/federal-government-budgets/basic-personal-amount.html
    - title: Income Tax Act (E), (A), (118.1), (1.1)
      href: https://laws-lois.justice.gc.ca/eng/acts/I-3.3/page-84.html?txthl=personal+amounts+amount+basic#s-118
    # Note: Unable to find primary CRA source for exact 2024-2025 base amounts
    # Values calculated using 4.7% (2024) and 2.7% (2025) indexation factors from T4127 
