description: Canada provides this base amount for the BPA.
values:
  2020-01-01: 12_298
  2021-01-01: 12_421
  2022-01-01: 12_719
  2023-01-01: 13_521
  2024-01-01: 14_156
  2025-01-01: 14_538
metadata:
  unit: currency-CAD
  period: year
  label: Basic personal amount base
  reference:
    - title: Government of Canada - Basic Personal amount
      href: https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/federal-government-budgets/basic-personal-amount.html
    - title: Income Tax Act (E), (A), (118.1), (1.1)
      href: https://laws-lois.justice.gc.ca/eng/acts/I-3.3/page-84.html?txthl=personal+amounts+amount+basic#s-118
    - title: T4127 Payroll Deductions Formulas - 117th Edition (2023 BPA = $13,521)
      href: https://www.canada.ca/en/revenue-agency/services/forms-publications/payroll/payroll-deductions-t4127-payroll-deductions-formulas/t4127-jan-117th-edition-effective-january-1-2023/t4127-jan-payroll-deductions-formulas.html
    - title: T4127 Payroll Deductions Formulas - 119th Edition (2024 BPA = $14,156)
      href: https://www.canada.ca/en/revenue-agency/services/forms-publications/payroll/payroll-deductions-t4127-payroll-deductions-formulas/t4127-jan-119th-edition-effective-january-1-2024/t4127-jan-payroll-deductions-formulas-computer-programs.html
    - title: T4127 Payroll Deductions Formulas - 120th Edition (2025 BPA = $14,538)
      href: https://www.canada.ca/en/revenue-agency/services/forms-publications/payroll/t4127-payroll-deductions-formulas/t4127-jan/t4127-jan-payroll-deductions-formulas-computer-programs.html 
